### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/jooveMovieApp#1]
Hi @eduardorasgado , can I create also a logo for this project?

Best Regards!

**Comment by eduardorasgado** [comment]
Sure bro, this is an app to watch movies in your tablet or smarthphone :) Try something! Thanks again.

**Comment by zuurw** [comment]
Hi @eduardorasgado I create this tree logos for this app, see if you like one of this.

Best regards

![logo proposal](https://user-images.githubusercontent.com/40801473/43040902-05d02094-8d49-11e8-8869-6feae46efbf9.png)

**Comment by eduardorasgado** [comment]
So awesome bro! I really like all the designs, #6 and #8 really expressed what i want to deliver to my customers. I think we could try something more like #8, it is interesting, modern but classic. What do you think? Send me a pull request :1st_place_medal: @zuurw

**Comment by zuurw** [comment]
Hi @eduardorasgado, the #8 was my first design :) and thats the one that I like most, I will make a PR, but I have to find a great font for the logotype, I dont like the one that I put, I will try to find one that looks good on the logo.

Best Regards!

**Comment by zuurw** [comment]
Hi @eduardorasgado, I create different logotypes with different fonts, see if you like one of this.

![logo proposal typeface2](https://user-images.githubusercontent.com/40801473/43129852-2fb2b256-8f2d-11e8-94c2-da2fa89d7dc2.png)

**Comment by eduardorasgado** [comment]
Hey @zuurw I really like the #3 one and #2 but i will let you the final decision mate! Thanks for the collab. Send me the PR.

**Comment by zuurw** [comment]
Hi @eduardorasgado I think Im going for the #2 :)

**Comment by zuurw** [comment]
Job done!
