### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/jooveMovieApp#2]
Hi @eduardorasgado  you should have a readme file with usage and install instructions of this project, it will have more visibility to other contributers like me.

Greetings!

**Comment by eduardorasgado** [comment]
Hi mate! There is already a README.md, the reason there is no instructions yet is because It is still in development mate, I will apply the changes inmediately after finishing the project :100:

**Comment by zuurw** [comment]
Ok
